// Code generated by MockGen. DO NOT EDIT.
// Source: ./interactive_service.go

// Package svcmocks is a generated GoMock package.
package svcmocks

import (
	domain "bbs-web/internal/domain"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockInteractiveService is a mock of InteractiveService interface.
type MockInteractiveService struct {
	ctrl     *gomock.Controller
	recorder *MockInteractiveServiceMockRecorder
}

// MockInteractiveServiceMockRecorder is the mock recorder for MockInteractiveService.
type MockInteractiveServiceMockRecorder struct {
	mock *MockInteractiveService
}

// NewMockInteractiveService creates a new mock instance.
func NewMockInteractiveService(ctrl *gomock.Controller) *MockInteractiveService {
	mock := &MockInteractiveService{ctrl: ctrl}
	mock.recorder = &MockInteractiveServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInteractiveService) EXPECT() *MockInteractiveServiceMockRecorder {
	return m.recorder
}

// CancelLike mocks base method.
func (m *MockInteractiveService) CancelLike(ctx context.Context, biz string, id, id2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelLike", ctx, biz, id, id2)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelLike indicates an expected call of CancelLike.
func (mr *MockInteractiveServiceMockRecorder) CancelLike(ctx, biz, id, id2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelLike", reflect.TypeOf((*MockInteractiveService)(nil).CancelLike), ctx, biz, id, id2)
}

// CollectArt mocks base method.
func (m *MockInteractiveService) CollectArt(ctx context.Context, biz string, bizId, uId, cId int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CollectArt", ctx, biz, bizId, uId, cId)
	ret0, _ := ret[0].(error)
	return ret0
}

// CollectArt indicates an expected call of CollectArt.
func (mr *MockInteractiveServiceMockRecorder) CollectArt(ctx, biz, bizId, uId, cId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CollectArt", reflect.TypeOf((*MockInteractiveService)(nil).CollectArt), ctx, biz, bizId, uId, cId)
}

// CollectEntity mocks base method.
func (m *MockInteractiveService) CollectEntity(ctx context.Context, biz string, uid, cid, bizId int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CollectEntity", ctx, biz, uid, cid, bizId)
	ret0, _ := ret[0].(error)
	return ret0
}

// CollectEntity indicates an expected call of CollectEntity.
func (mr *MockInteractiveServiceMockRecorder) CollectEntity(ctx, biz, uid, cid, bizId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CollectEntity", reflect.TypeOf((*MockInteractiveService)(nil).CollectEntity), ctx, biz, uid, cid, bizId)
}

// CreateCollect mocks base method.
func (m *MockInteractiveService) CreateCollect(ctx context.Context, uid int64, cname, desc string, isPub bool) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCollect", ctx, uid, cname, desc, isPub)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCollect indicates an expected call of CreateCollect.
func (mr *MockInteractiveServiceMockRecorder) CreateCollect(ctx, uid, cname, desc, isPub interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCollect", reflect.TypeOf((*MockInteractiveService)(nil).CreateCollect), ctx, uid, cname, desc, isPub)
}

// Get mocks base method.
func (m *MockInteractiveService) Get(ctx context.Context, biz string, id, uid int64) (domain.Interactive, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, biz, id, uid)
	ret0, _ := ret[0].(domain.Interactive)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockInteractiveServiceMockRecorder) Get(ctx, biz, id, uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockInteractiveService)(nil).Get), ctx, biz, id, uid)
}

// GetByIds mocks base method.
func (m *MockInteractiveService) GetByIds(ctx context.Context, biz string, ids []int64) (map[int64]domain.Interactive, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIds", ctx, biz, ids)
	ret0, _ := ret[0].(map[int64]domain.Interactive)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIds indicates an expected call of GetByIds.
func (mr *MockInteractiveServiceMockRecorder) GetByIds(ctx, biz, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIds", reflect.TypeOf((*MockInteractiveService)(nil).GetByIds), ctx, biz, ids)
}

// GetByUid mocks base method.
func (m *MockInteractiveService) GetByUid(ctx context.Context, uid, limit, offset int64) ([]domain.Collect, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUid", ctx, uid, limit, offset)
	ret0, _ := ret[0].([]domain.Collect)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUid indicates an expected call of GetByUid.
func (mr *MockInteractiveServiceMockRecorder) GetByUid(ctx, uid, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUid", reflect.TypeOf((*MockInteractiveService)(nil).GetByUid), ctx, uid, limit, offset)
}

// IncrReadCnt mocks base method.
func (m *MockInteractiveService) IncrReadCnt(ctx context.Context, biz string, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrReadCnt", ctx, biz, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrReadCnt indicates an expected call of IncrReadCnt.
func (mr *MockInteractiveServiceMockRecorder) IncrReadCnt(ctx, biz, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrReadCnt", reflect.TypeOf((*MockInteractiveService)(nil).IncrReadCnt), ctx, biz, id)
}

// Like mocks base method.
func (m *MockInteractiveService) Like(ctx context.Context, biz string, id, id2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Like", ctx, biz, id, id2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Like indicates an expected call of Like.
func (mr *MockInteractiveServiceMockRecorder) Like(ctx, biz, id, id2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Like", reflect.TypeOf((*MockInteractiveService)(nil).Like), ctx, biz, id, id2)
}
