// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"bbs-micro/bbs-interactive/events"
	"bbs-micro/bbs-interactive/grpc"
	"bbs-micro/bbs-interactive/ioc"
	"bbs-micro/bbs-interactive/repository"
	"bbs-micro/bbs-interactive/repository/cache"
	"bbs-micro/bbs-interactive/repository/dao"
	"bbs-micro/bbs-interactive/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitApp(path string) *App {
	config := ioc.InitConfig(path)
	logger := ioc.InitLogger()
	db := ioc.InitDatabase(config)
	interactiveDao := dao.NewInteractiveDao(db)
	cmdable := ioc.InitRedis(config)
	redisInteractiveCache := cache.NewRedisInteractiveCache(cmdable)
	interactiveRepo := repository.NewInteractiveRepo(logger, interactiveDao, redisInteractiveCache)
	interactiveService := service.NewInteractiveService(interactiveRepo, logger)
	interactiveServiceServer := grpc.NewInteractiveServiceServer(interactiveService)
	serverX := ioc.InitGRPCXServer(config, interactiveServiceServer, logger)
	client := ioc.InitSaramaClient(config)
	consumer := events.NewInteractiveReadEventBatchConsumer(client, logger, interactiveRepo)
	v := ioc.InitConsumer(consumer)
	app := &App{
		server:   serverX,
		consumer: v,
	}
	return app
}

// wire.go:

var thirdPartySet = wire.NewSet(ioc.InitConfig, ioc.InitLogger, ioc.InitRedis, ioc.InitDatabase, ioc.InitSaramaClient, ioc.InitConsumer, ioc.InitGRPCXServer, events.NewInteractiveReadEventBatchConsumer)

var interactiveSvcProvider = wire.NewSet(dao.NewInteractiveDao, cache.NewRedisInteractiveCache, repository.NewInteractiveRepo, service.NewInteractiveService)
