// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"enterprise360/service/user/rpc/internal/logic"
	"enterprise360/service/user/rpc/internal/svc"
	"enterprise360/service/user/rpc/types/user"
)

type UserCenterServiceServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserCenterServiceServer
}

func NewUserCenterServiceServer(svcCtx *svc.ServiceContext) *UserCenterServiceServer {
	return &UserCenterServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *UserCenterServiceServer) Login(ctx context.Context, in *user.LoginRequest) (*user.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}
