// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	article2 "bbs-micro/bbs-bff/internal/events/article"
	"bbs-micro/bbs-bff/internal/ioc"
	"bbs-micro/bbs-bff/internal/repository"
	"bbs-micro/bbs-bff/internal/repository/article"
	"bbs-micro/bbs-bff/internal/repository/cache"
	"bbs-micro/bbs-bff/internal/repository/dao"
	"bbs-micro/bbs-bff/internal/repository/dao/article_dao"
	"bbs-micro/bbs-bff/internal/service"
	article3 "bbs-micro/bbs-bff/internal/service/article"
	"bbs-micro/bbs-bff/internal/web"
	"bbs-micro/bbs-bff/internal/web/handler"
	"bbs-micro/bbs-bff/internal/web/jwtx"
)

// Injectors from wire.go:

func InitWebServer(path string) *App {
	config := ioc.InitConfig(path)
	db := ioc.InitDatabase(config)
	articleDAO := article_dao.NewGormArticleDao(db)
	cmdable := ioc.InitRedis(config)
	articleCache := cache.NewArticleCache(cmdable)
	logger := ioc.InitLogger()
	iUserDao := dao.NewUserDao(db)
	iUserRepo := repository.NewUserRepo(iUserDao)
	articleRepository := article.NewArticleRepo(articleDAO, articleCache, logger, iUserRepo)
	writeDAO := article_dao.NewWriteDAO(db)
	artWriterRepo := article.NewArtWriterRepo(writeDAO)
	readDAO := article_dao.NewReadDAO(db)
	articleReaderRepository := article.NewArticleReaderRepo(readDAO)
	client := ioc.InitSaramaClient(config)
	syncProducer := ioc.InitSyncProducer(client)
	producer := article2.NewProducer(syncProducer)
	iArticleService := article3.NewArticleService(articleRepository, logger, artWriterRepo, articleReaderRepository, producer)
	interactiveDao := dao.NewInteractiveDao(db)
	redisInteractiveCache := cache.NewRedisInteractiveCache(cmdable)
	interactiveRepo := repository.NewInteractiveRepo(interactiveDao, redisInteractiveCache, logger)
	interactiveService := service.NewInteractiveService(interactiveRepo, redisInteractiveCache)
	interactiveServiceClient := ioc.InitInterGRPCClient(interactiveService, config)
	articleHandler := handler.NewArticleHandler(iArticleService, interactiveServiceClient, logger)
	iCaptchaSvc := service.NewCaptchaService()
	captchaHandler := handler.NewCaptchaHandler(iCaptchaSvc)
	iUserService := service.NewUserService(iUserRepo)
	jwtHandler := jwtx.NewRedisJWTHandler(cmdable)
	userHandler := handler.NewUserHandler(iUserService, iCaptchaSvc, jwtHandler)
	router := web.NewRouter(articleHandler, captchaHandler, userHandler)
	v := ioc.InitMiddleware(config, jwtHandler)
	engine := ioc.InitGin(router, v)
	consumer := article2.NewInteractiveReadEventBatchConsumer(client, logger, interactiveRepo)
	v2 := ioc.InitConsumer(consumer)
	app := &App{
		server:    engine,
		consumers: v2,
	}
	return app
}
