
service_name: "bbs_spider_1"
service_env: "dev"
service_id: 1
service_port: ":8002"
service_version: "v0.0.1"
prometheus_port: ":8001"
language: "zh"

database:
  dsn: "admin:123456@tcp(192.168.1.52:3306)/bbs-gin?charset=utf8mb4&parseTime=True&loc=Local"
  max_idle_conn: 10  # 最大空闲连接数
  max_open_conn: 10  # 最大连接数

redis:
  dsn: "192.168.1.52:6379"a

mongodb:
  dsn: "mongodb://root:example@localhost:27017"

kafka:
  borkers:
    - "192.168.1.52:9094"

otel:
  url: "http://192.168.1.52:14268/api/traces"